gems: []
download_url_mac: https://s3.amazonaws.com/speak-production-releases/darwin/install-speak.dmg
bulldog_url: http://docker:9393
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      header_description: true
  -
    scope:
      path: "tools-for-remote-workers-digital-nomads"
    values:
      header_description: false
      class: tools
      color: 4A90E2
      script: tools.js
exclude: [
  vendor,
  circle.yml,
  Dockerfile,
  deploy.sh,
  Gemfile,
  Gemfile.lock,
  README.md
]
category-list: [communication, productivity, fun, travel]
