gems: []
download_url_mac: https://releases.speak.io/darwin/install-speak.dmg
download_url_win: https://releases.speak.io/win32/SpeakSetup.exe
download_url_linux: http://help.speak.io/article/43-speak-for-linux
bulldog_url: http://docker:9393
keen_project_id: '54cb8b0e46f9a73b4b13f4f7'
keen_write_key: 'ca31410e622e6ce3b25213a3e13a1a5b9f63e172b135ffafb65fa93e975fb2d454f74353fc99be542979813fe24d7c93a4d988e6fe344ed2b5b54fa20a88c543624fdec2b865bf86a28f17d2e7d3dba74fecd63a4f6dad3c388a9ef83b23a8a0c3137ad3552b4e26f7fb9e5e96d157d3'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      header_description: true
      color: 4A90E2
  -
    scope:
      path: "tools-for-remote-workers-digital-nomads"
    values:
      header_description: false
      class: tools
      color: 4A90E2
      script: tools.js
exclude: [
  vendor,
  circle.yml,
  Dockerfile,
  deploy.sh,
  Gemfile,
  Gemfile.lock,
  README.md
]
category-list: [communication, productivity, fun, travel]
